2022-09-23 21:20:13,149 INFO Watching for file changes with StatReloader 636 
2022-09-23 21:20:18,575 WARNING Not Found: / 224 
2022-09-23 21:20:18,576 WARNING "GET / HTTP/1.1" 404 4803 161 
2022-09-23 21:20:19,102 WARNING Not Found: /favicon.ico 224 
2022-09-23 21:20:19,104 WARNING "GET /favicon.ico HTTP/1.1" 404 4854 161 
2022-09-23 21:20:25,901 INFO "GET /admin HTTP/1.1" 301 0 161 
2022-09-23 21:20:26,021 ERROR Internal Server Error: /admin/ 224 
Traceback (most recent call last):
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\sessions\backends\base.py", line 233, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\admin\sites.py", line 250, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\admin\sites.py", line 221, in inner
    if not self.has_permission(request):
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\admin\sites.py", line 195, in has_permission
    return request.user.is_active and request.user.is_staff
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\functional.py", line 246, in inner
    self._setup()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\functional.py", line 382, in _setup
    self._wrapped = self._setupfunc()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\__init__.py", line 177, in get_user
    user_id = _get_user_session_key(request)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\sessions\backends\base.py", line 65, in __getitem__
    return self._session[key]
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\sessions\backends\base.py", line 238, in _get_session
    self._session_cache = self.load()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\sessions\backends\db.py", line 43, in load
    s = self._get_session_from_db()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1162, in execute_sql
    sql, params = self.as_sql()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 513, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 55, in pre_sql_setup
    self.setup_query()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 46, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 262, in get_select
    sql, params = self.compile(col)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 445, in compile
    sql, params = node.as_sql(self, self.connection)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\expressions.py", line 835, in as_sql
    sql = '.'.join(map(compiler.quote_name_unless_alias, identifiers))
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 436, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\dummy\base.py", line 20, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
2022-09-23 21:20:26,031 ERROR "GET /admin/ HTTP/1.1" 500 187309 161 
2022-09-23 21:20:43,191 WARNING Not Found: / 224 
2022-09-23 21:20:43,192 WARNING "GET / HTTP/1.1" 404 4803 161 
2022-09-23 21:20:51,537 ERROR Internal Server Error: /admin/ 224 
Traceback (most recent call last):
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\sessions\backends\base.py", line 233, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\admin\sites.py", line 250, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\admin\sites.py", line 221, in inner
    if not self.has_permission(request):
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\admin\sites.py", line 195, in has_permission
    return request.user.is_active and request.user.is_staff
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\functional.py", line 246, in inner
    self._setup()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\utils\functional.py", line 382, in _setup
    self._wrapped = self._setupfunc()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\__init__.py", line 177, in get_user
    user_id = _get_user_session_key(request)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\auth\__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\sessions\backends\base.py", line 65, in __getitem__
    return self._session[key]
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\sessions\backends\base.py", line 238, in _get_session
    self._session_cache = self.load()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\sessions\backends\db.py", line 43, in load
    s = self._get_session_from_db()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 1162, in execute_sql
    sql, params = self.as_sql()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 513, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 55, in pre_sql_setup
    self.setup_query()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 46, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 262, in get_select
    sql, params = self.compile(col)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 445, in compile
    sql, params = node.as_sql(self, self.connection)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\expressions.py", line 835, in as_sql
    sql = '.'.join(map(compiler.quote_name_unless_alias, identifiers))
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\compiler.py", line 436, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "C:\Users\97798\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\backends\dummy\base.py", line 20, in complain
    raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
2022-09-23 21:20:51,539 ERROR "GET /admin/ HTTP/1.1" 500 187309 161 
